services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: jump
      POSTGRES_USER: jump
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/18/docker
    networks:
      - jump-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jump"]
      interval: 5s
      timeout: 5s
      retries: 5

  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    restart: unless-stopped
    ports:
      - "3900:3900"   # API S3
      - "3903:3903"   # Admin API
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data

  garage-webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    ports:
      - "3909:3909"
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
    depends_on:
      - garage


  sveltekit:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jump-network
    environment:
      - PORT=${PORT}
      - ORIGIN=${ORIGIN}
      - DATABASE_URL=postgresql://jump:${POSTGRES_PASSWORD}@postgres:5432/jump
      - HOST_HEADER=x-forwarded-host
    restart: unless-stopped

volumes:
  pg_data:

networks:
  jump-network:
    driver: bridge
