/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("pbc_2651147324")

  // update collection data
  unmarshal({
    "confirmEmailChangeTemplate": {
      "body": "<div style=\"background-color: #f8fafc; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; text-align: center;\">\n  <div style=\"max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 24px; padding: 40px 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); border-top: 5px solid #00ff97; text-align: left;\">\n    <p style=\"font-size: 16px; line-height: 1.6; margin-top: 0; margin-bottom: 20px;\">Salut <strong>{RECORD:prenom}</strong>,</p>\n    <p style=\"font-size: 16px; line-height: 1.6; margin-bottom: 30px;\">Tu as demandé à modifier ton adresse email de contact. Clique sur le bouton ci-dessous pour confirmer cette nouvelle adresse.</p>\n    <div style=\"text-align: center; margin-bottom: 30px;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb !important; color: #ffffff !important; text-decoration: none !important; padding: 14px 28px !important; border-radius: 12px !important; font-weight: bold; font-size: 16px; box-shadow: 0 4px 14px rgba(1, 58, 251, 0.3); line-height: normal !important; font-family: inherit !important;\">Confirmer mon nouvel email</a>\n    </div>\n    <div style=\"background-color: #f1f5f9; padding: 15px; border-radius: 12px; margin-bottom: 20px;\">\n      <p style=\"font-size: 13px; color: #64748b; margin: 0;\"><i>Si tu n'as pas fait cette demande, ignore cet email pour que rien ne change sur ton compte.</i></p>\n    </div>\n    <p style=\"font-size: 14px; color: #64748b; margin: 0;\">À très vite,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    },
    "resetPasswordTemplate": {
      "body": "<div style=\"background-color: #f8fafc; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; text-align: center;\">\n  <div style=\"max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 24px; padding: 40px 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); border-top: 5px solid #00ff97; text-align: left;\">\n    <p style=\"font-size: 16px; line-height: 1.6; margin-top: 0; margin-bottom: 20px;\">Salut <strong>{RECORD:prenom}</strong>,</p>\n    <p style=\"font-size: 16px; line-height: 1.6; margin-bottom: 30px;\">Tu as oublié ton mot de passe ? Pas de panique ! Clique sur le bouton ci-dessous pour en créer un nouveau et retrouver l'accès à tes missions.</p>\n    <div style=\"text-align: center; margin-bottom: 30px;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb !important; color: #ffffff !important; text-decoration: none !important; padding: 14px 28px !important; border-radius: 12px !important; font-weight: bold; font-size: 16px; box-shadow: 0 4px 14px rgba(1, 58, 251, 0.3); line-height: normal !important; font-family: inherit !important;\">Réinitialiser mon mot de passe</a>\n    </div>\n    <div style=\"background-color: #f1f5f9; padding: 15px; border-radius: 12px; margin-bottom: 20px;\">\n      <p style=\"font-size: 13px; color: #64748b; margin: 0;\"><i>Si tu n'as rien demandé, tu peux simplement ignorer cet email, ton compte est en sécurité.</i></p>\n    </div>\n    <p style=\"font-size: 14px; color: #64748b; margin: 0;\">Bon code,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    }
  }, collection)

  return app.save(collection)
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_2651147324")

  // update collection data
  unmarshal({
    "confirmEmailChangeTemplate": {
      "body": "<div style=\"background-color: #f8fafc; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; text-align: center;\">\n  <div style=\"max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 24px; padding: 40px 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); border-top: 5px solid #00ff97; text-align: left;\">\n    <p style=\"font-size: 16px; line-height: 1.6; margin-top: 0; margin-bottom: 20px;\">Salut <strong>{RECORD:prenom}</strong>,</p>\n    <p style=\"font-size: 16px; line-height: 1.6; margin-bottom: 30px;\">Tu as demandé à modifier ton adresse email de contact. Clique sur le bouton ci-dessous pour confirmer cette nouvelle adresse.</p>\n    <div style=\"text-align: center; margin-bottom: 30px;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 12px; font-weight: bold; font-size: 16px; box-shadow: 0 4px 14px rgba(1, 58, 251, 0.3);\">Confirmer mon nouvel email</a>\n    </div>\n    <div style=\"background-color: #f1f5f9; padding: 15px; border-radius: 12px; margin-bottom: 20px;\">\n      <p style=\"font-size: 13px; color: #64748b; margin: 0;\"><i>Si tu n'as pas fait cette demande, ignore cet email pour que rien ne change sur ton compte.</i></p>\n    </div>\n    <p style=\"font-size: 14px; color: #64748b; margin: 0;\">À très vite,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    },
    "resetPasswordTemplate": {
      "body": "<div style=\"background-color: #f8fafc; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; text-align: center;\">\n  <div style=\"max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 24px; padding: 40px 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); border-top: 5px solid #00ff97; text-align: left;\">\n    <p style=\"font-size: 16px; line-height: 1.6; margin-top: 0; margin-bottom: 20px;\">Salut <strong>{RECORD:prenom}</strong>,</p>\n    <p style=\"font-size: 16px; line-height: 1.6; margin-bottom: 30px;\">Tu as oublié ton mot de passe ? Pas de panique ! Clique sur le bouton ci-dessous pour en créer un nouveau et retrouver l'accès à tes missions.</p>\n    <div style=\"text-align: center; margin-bottom: 30px;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 12px; font-weight: bold; font-size: 16px; box-shadow: 0 4px 14px rgba(1, 58, 251, 0.3);\">Réinitialiser mon mot de passe</a>\n    </div>\n    <div style=\"background-color: #f1f5f9; padding: 15px; border-radius: 12px; margin-bottom: 20px;\">\n      <p style=\"font-size: 13px; color: #64748b; margin: 0;\"><i>Si tu n'as rien demandé, tu peux simplement ignorer cet email, ton compte est en sécurité.</i></p>\n    </div>\n    <p style=\"font-size: 14px; color: #64748b; margin: 0;\">Bon code,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    }
  }, collection)

  return app.save(collection)
})
