/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("_pb_users_auth_")

  // update collection data
  unmarshal({
    "confirmEmailChangeTemplate": {
      "body": "<div style=\"background-color: #f1f5f9; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #0f172a;\">\n  <div style=\"max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 4px; padding: 30px; border-top: 4px solid #013afb; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0;\">\n    <p style=\"font-size: 15px; line-height: 1.6; margin-top: 0;\">Bonjour <strong>{RECORD:name}</strong>,</p>\n    <p style=\"font-size: 15px; line-height: 1.6;\">Vous avez initié une procédure de modification de votre adresse email sur <strong>{APP_NAME}</strong>. Veuillez cliquer sur le lien ci-dessous pour confirmer cette nouvelle adresse.</p>\n    <p style=\"margin: 25px 0;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb !important; color: #ffffff !important; text-decoration: none !important; padding: 10px 20px !important; border-radius: 4px !important; font-weight: bold; font-size: 14px; line-height: normal !important; font-family: inherit !important;\">Confirmer la nouvelle adresse</a>\n    </p>\n    <p style=\"font-size: 13px; color: #64748b;\"><i>Si vous n'avez pas demandé ce changement, aucune action n'est requise de votre part.</i></p>\n    <p style=\"font-size: 13px; color: #64748b; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 15px;\">Cordialement,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    },
    "resetPasswordTemplate": {
      "body": "<div style=\"background-color: #f1f5f9; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #0f172a;\">\n  <div style=\"max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 4px; padding: 30px; border-top: 4px solid #013afb; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0;\">\n    <p style=\"font-size: 15px; line-height: 1.6; margin-top: 0;\">Bonjour <strong>{RECORD:name}</strong>,</p>\n    <p style=\"font-size: 15px; line-height: 1.6;\">Une demande de réinitialisation de mot de passe a été effectuée pour votre compte sur <strong>{APP_NAME}</strong>. Cliquez sur le lien ci-dessous pour définir un nouveau mot de passe.</p>\n    <p style=\"margin: 25px 0;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb !important; color: #ffffff !important; text-decoration: none !important; padding: 10px 20px !important; border-radius: 4px !important; font-weight: bold; font-size: 14px; line-height: normal !important; font-family: inherit !important;\">Réinitialiser le mot de passe</a>\n    </p>\n    <p style=\"font-size: 13px; color: #64748b;\"><i>Si vous n'êtes pas à l'origine de cette demande, veuillez ignorer cet email.</i></p>\n    <p style=\"font-size: 13px; color: #64748b; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 15px;\">Cordialement,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    }
  }, collection)

  return app.save(collection)
}, (app) => {
  const collection = app.findCollectionByNameOrId("_pb_users_auth_")

  // update collection data
  unmarshal({
    "confirmEmailChangeTemplate": {
      "body": "<div style=\"background-color: #f1f5f9; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #0f172a;\">\n  <div style=\"max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 4px; padding: 30px; border-top: 4px solid #013afb; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0;\">\n    <p style=\"font-size: 15px; line-height: 1.6; margin-top: 0;\">Bonjour <strong>{RECORD:name}</strong>,</p>\n    <p style=\"font-size: 15px; line-height: 1.6;\">Vous avez initié une procédure de modification de votre adresse email sur <strong>{APP_NAME}</strong>. Veuillez cliquer sur le lien ci-dessous pour confirmer cette nouvelle adresse.</p>\n    <p style=\"margin: 25px 0;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb; color: #ffffff; text-decoration: none; padding: 10px 20px; border-radius: 4px; font-weight: bold; font-size: 14px;\">Confirmer la nouvelle adresse</a>\n    </p>\n    <p style=\"font-size: 13px; color: #64748b;\"><i>Si vous n'avez pas demandé ce changement, aucune action n'est requise de votre part.</i></p>\n    <p style=\"font-size: 13px; color: #64748b; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 15px;\">Cordialement,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    },
    "resetPasswordTemplate": {
      "body": "<div style=\"background-color: #f1f5f9; padding: 40px 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #0f172a;\">\n  <div style=\"max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 4px; padding: 30px; border-top: 4px solid #013afb; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0;\">\n    <p style=\"font-size: 15px; line-height: 1.6; margin-top: 0;\">Bonjour <strong>{RECORD:name}</strong>,</p>\n    <p style=\"font-size: 15px; line-height: 1.6;\">Une demande de réinitialisation de mot de passe a été effectuée pour votre compte sur <strong>{APP_NAME}</strong>. Cliquez sur le lien ci-dessous pour définir un nouveau mot de passe.</p>\n    <p style=\"margin: 25px 0;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; background-color: #013afb; color: #ffffff; text-decoration: none; padding: 10px 20px; border-radius: 4px; font-weight: bold; font-size: 14px;\">Réinitialiser le mot de passe</a>\n    </p>\n    <p style=\"font-size: 13px; color: #64748b;\"><i>Si vous n'êtes pas à l'origine de cette demande, veuillez ignorer cet email.</i></p>\n    <p style=\"font-size: 13px; color: #64748b; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 15px;\">Cordialement,<br/>L'équipe Epitech Academy</p>\n  </div>\n</div>"
    }
  }, collection)

  return app.save(collection)
})
